### ISSUE TITLE
Results do not match pre-rendered PDFs

### ISSUE THREAD

**Issue by AlbertoGP** [speedata/examples#1]
Hi, just installed SP right now and it seems that something is off.

The magazine example produces three pages because the titles ("par@title") have bigger top and bottom margin/padding, an the first paragraph with the drop initial "T" also has some space on top so it does not align with the the picture on the right.

Then I've tried the news example, and there we have bigger problems as you can see in the attachment.

I get the same results with both 2.8.1 (stable) and 2.9.5 (development), installed for the first time a few minutes ago, in Ubuntu Linux 16.04.

Is this expected? Is there something I can check on my part to figure this out?

![sp-example-news-20170319](https://cloud.githubusercontent.com/assets/2456465/24080328/f168c9f4-0c9c-11e7-8204-3fab7fc1d737.png)

**Comment by pgundlach** [comment]
Thank you very much for the report, I'll fix it as soon as possible.

**Comment by pgundlach** [comment]
This was due to a change in the cursor behaviour, the NextRow semantic is now cleaner (IMO). So thank you again for your report, and if you have any questions, don't hesitate to contact me.
